-- 演示库表结构（H2 内存库，启动时重建）
drop table if exists sys_user;
drop table if exists sys_user_perm;
drop table if exists product;

create table sys_user (
    id          bigint generated by default as identity primary key,
    username    varchar(50)  not null,
    nickname    varchar(50),
    password    varchar(100),
    email       varchar(100),
    status      int          default 1,
    create_time timestamp,
    update_time timestamp
);

create table sys_user_perm (
    id        bigint generated by default as identity primary key,
    user_id   bigint       not null,
    perm_code varchar(100) not null
);

create table product (
    id          varchar(32) primary key,
    name        varchar(100),
    price       decimal(10, 2),
    stock       int,
    create_time timestamp,
    update_time timestamp
);
